repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: mixed-line-ending
      - id: check-case-conflict
      - id: check-yaml
  - repo: https://github.com/benjeffery/pre-commit-clang-format
    rev: master
    hooks:
    - id: clang-format
      exclude: dev-tools|examples
      verbose: true
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.5
    hooks:
      - id: reorder-python-imports
        args: [--application-directories=python,
               --unclassifiable-application-module=_tskit]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.2
    hooks:
      - id: pyupgrade
        args: [--py3-plus, --py36-plus]
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3
        # We have to be specific here as python/lib contains a symlink
        # loop that throws an error before black excludes it
        args: [python/tskit, python/setup.py, python/stress_lowlevel.py]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        args: [--config=python/.flake8]
        additional_dependencies: ["flake8-bugbear==20.1.4", "flake8-builtins==1.5.2"]
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.8.0
    hooks:
      - id: blacken-docs
        args: [--skip-errors]
        additional_dependencies: [black==20.8b1]
        language_version: python3
